/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Noto Sans JP', 'sans-serif'],
        headline: ['Epilogue', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      colors: {
        "on-primary": "#650005",
        "surface-container-low": "#131313",
        "on-error-container": "#ffb2b9",
        "surface-container-lowest": "#000000",
        "on-secondary-fixed-variant": "#004baf",
        "surface-tint": "#ff8e82",
        "on-primary-fixed": "#000000",
        "on-surface": "#ffffff",
        "inverse-surface": "#fcf9f8",
        "secondary-container": "#0058cb",
        "on-secondary-container": "#f7f7ff",
        "surface-container-highest": "#262626",
        "on-primary-container": "#4f0003",
        "on-background": "#ffffff",
        "background": "#0e0e0e",
        "error": "#ff6e84",
        "on-primary-fixed-variant": "#600004",
        "surface-container-high": "#201f1f",
        "secondary-dim": "#076df6",
        "error-dim": "#d73357",
        "surface-variant": "#262626",
        "primary-dim": "#ea031a",
        "error-container": "#a70138",
        "on-tertiary-fixed-variant": "#54197f",
        "outline-variant": "#484847",
        "tertiary-fixed": "#d398ff",
        "inverse-on-surface": "#565555",
        "secondary-fixed": "#c1d1ff",
        "on-tertiary-fixed": "#290045",
        "secondary-fixed-dim": "#acc3ff",
        "on-tertiary-container": "#43006d",
        "tertiary-dim": "#c085ed",
        "on-error": "#490013",
        "primary-fixed-dim": "#ff5b4f",
        "surface-container": "#1a1919",
        "tertiary": "#d7a0ff",
        "secondary": "#6e9bff",
        "on-secondary-fixed": "#003076",
        "primary": "#ff8e82",
        "primary-container": "#ff766a",
        "primary-fixed": "#ff766a",
        "on-tertiary": "#4f127a",
        "on-surface-variant": "#adaaaa",
        "surface": "#0e0e0e",
        "surface-bright": "#2c2c2c",
        "outline": "#767575",
        "surface-dim": "#0e0e0e",
        "on-secondary": "#001d4e",
        "tertiary-container": "#cb8ff9",
        "tertiary-fixed-dim": "#c68af3",
        "inverse-primary": "#c10012"
      },
      screens: {
        '3xl': '1920px',
        '4xl': '2560px',
      },
      aspectRatio: {
        poster: '2 / 3',
        cinema: '21 / 9',
      },
      zIndex: {
        backdrop: 10,
        gradient: 20,
        overlay: 30,
        modal: 40,
        toast: 50,
      },
    },
  },
  plugins: [],
};
